output:
	make -C../problem8 -f makefile
	make -C../problem9 -f makefile
	make -C../problem10 -f makefile

clean:
	cd ../problem8 ; make clean
	cd ../problem9 ; make clean
	cd ../problem10 ; make clean
